import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_components/Header";
import styles from "./layout.module.css";
import "./_styles/global.css";

import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Show random posts app",
  description: "Allows to see posts and comments generated by jsonplaceholder",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <Header />
        <div className={styles.main}>{children}</div>
      </body>
    </html>
  );
}
